/******************************************************
* PLEASE DO NOT EDIT THIS FILE
* the verification process may break
* ***************************************************/

//'use strict';

const dateFormat = require('dateFormat');
var fs = require('fs');
var express = require('express');
var app = express();

function isNumeric(num) {
  return !isNaN(num)
}

function isNumeric(num) {
  return !isNaN(num)
}

if (!process.env.DISABLE_XORIGIN) {
  app.use(function (req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if (!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1) {
      console.log(origin);
      res.setHeader('Access-Control-Allow-Origin', origin);
      res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function (req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function (err, data) {
      if (err) return next(err);
      res.type('txt').send(data.toString());
    });
  });

app.route('/')
  .get(function (req, res) {
    res.sendFile(process.cwd() + '/views/index.html');
  });

app.route('/:time').get(function (req, res) {
  var time = req.params.time;
  var result = {
    "unix": null,
    "natural": null
  };
  var date = null;
  try {
    if (isNumeric(time)) {
      console.log("Is numeric");
      date = new Date(parseInt(time * 1000));
    }
    else {
      console.log("Not Is numeric: ", time);
      date = new Date(time);
    }
    result = {
      "unix":  Math.floor(date.getTime() / 1000),
      "natural": dateFormat(date, 'mmmm dd, yyyy')
    };
  }
  catch (e) {
    console.log("erreur date format time", time, " erreur : ", e);
  }
  res.send(result);
});

// Respond not found to all the wrong routes
app.use(function (req, res, next) {
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function (err, req, res, next) {
  if (err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }
})

var port = process.env.PORT || 3000;
app.listen(port, function () {
  console.log('Node.js listening on port', port, "...");
});

